# message ids

messageId = {
    'L1MM1_M00': '0xEF71',
    'L1MM1_M01': '0xEFE2',
    'L1MM1_M02': '0xE1C0',
    'L1MM1_M03': '0xEFE5',
    'L1MM1_M04': '0xEFC1',
    'L1MM1_M05': '0xEFC2',
    'L1MM1_M06': '0xE2D4',
    'L1MM1_M07': '0xE255',
    'L1MM1_M08': '0xE2D6',
    'L1MM1_M10': '0xEF81',
    'L1MM1_M11': '0xEF82',
    'L1MM1_M12': '0xEF91',
    'L1C1_M21': '0xEE11',
    'L1C1_M22': '0xEE12',
    'L1C1_M23': '0xEE13',
    'L1C1_M25': '0xEE10',
    'L1C2_M21': '0xEE21',
    'L1C2_M22': '0xEE22',
    'L1C3_M21': '0xEE31',
    'L1C3_M22': '0xEE32',
    'L1C4_M21': '0xEE41',
    'L1C4_M22': '0xEE42',
    'L1C5_M21': '0xEE51',
    'L1C5_M24': '0xEE52',
    'L1C5_M26': '0xEE53'
}

# telegram definition

teltype_M00 = [
    ('ActualDateTime', 'i4', 8)
]

teltype_N00 = [
    ('ActualDateTime', 'i4', 8)
]

teltype_M01 = [
    ('CoilId', 'S14'),
    ('CoilIdOut', 'S14'),
    ('InitiateFlag', 'i4')
]

teltype_M02 = [
    ('StandNo', 'i4'),
    ('RollId', 'S8', 6),
    ('ForceCalibOS', 'f4'),
    ('ForceCalibDS', 'f4'),
    ('BendCalibWROS', 'f4'),
    ('BendCalibWRDS', 'f4'),
    ('BendCalibIROS', 'f4'),
    ('BendCalibIRDS', 'f4'),
    ('ShiftCalib', 'f4'),
    ('HydPosCalibOS', 'f4'),
    ('HydPosCalibDS', 'f4'),
    ('WedgeAdjPosCalib', 'f4'),
    ('CalibDateTime', 'i4', 8),
    ('CalibMode', 'i4'),
    ('FloatSpare', 'f4', 5),
    ('IntegerSpare', 'i4', 5),
    ('CharSpare', 'S16')
]

teltype_M03 = [
    ('StandNo', 'i4')
]

teltype_M04 = [
    ('SystemId', 'i4'),
    ('AutoSetupMode', 'i4'),
    ('AutoCutMode', 'i4'),
    ('BatteryOn', 'i4'),
    ('BatteryLow', 'i4'),
    ('CoilPullMode', 'i4'),
    ('PullReqStatus', 'i4'),
    ('PullReqCoilId', 'S14'),
    ('PullReqPassNo', 'i4'),
    ('ThreadAssist', 'i4'),
    ('ThreadingMode', 'i4'),
    ('TailOutMode', 'i4'),
    ('RewindMode', 'i4'),
    ('ElongationMode', 'i4'),
    ('SynchTcmPlMode', 'i4'),
    ('SynchTcmPlSpeed', 'f4'),
    ('SingleReelMode', 'i4'),
    ('FloatSpare', 'f4', 5),
    ('IntegerSpare', 'i4', 5),
    ('CharSpare', 'S16')
]

teltype_M05 = [
    ('ConsElectEnergyAmount', 'i4'),
    ('ConsN2Amount', 'i4'),
    ('IntegerSpare', 'i4', 5),
    ('FloatSpare', 'f4', 5)
]

teltype_M06 = [
    ('CoilId', 'S14', 25),
    ('CoilIdOut', 'S14', 25),
    ('PdiOk', 'i4', 25),
    ('Occupied', 'i4', 25),
    ('PassRolled', 'i4', 25),
    ('DispositionCode', 'i4', 25),
    ('CoilCarPosition', 'f4', 1),
    ('SampleCutSegmNo', 'i4', 2)
]

teltype_M07 = [
    ('EventCode', 'i4'),
    ('CoilIdEntryDiam', 'S14'),
    ('EntryDiam', 'f4'),
    ('CoilIdEntryWidth', 'S14'),
    ('EntryWidth', 'f4'),
    ('CoilIdEntryTemp', 'S14'),
    ('EntryTemp', 'f4'),
    ('CoilIdExitTemp', 'S14'),
    ('ExitTemp', 'f4'),
    ('CoilIdOutExitWeight', 'S14'),
    ('ExitWeight', 'f4'),
    ('CoilIdOutStrapped', 'S14'),
    ('NoStraps', 'i4'),
    ('StrapCode', 'i4'),
    ('CoilIdOutMarked', 'S14'),
    ('MarkingId', 'S14'),
    ('CoilIdOutLabelPrint', 'S14'),
    ('FloatSpare', 'f4', 5),
    ('IntegerSpare', 'i4', 5),
    ('CharSpare', 'S16')
]

teltype_M08 = [
    ('ActualDateTime', 'i4', 8)
]

teltype_M10 = [
    ('InMillCoilId', 'S14', 2),
    ('InMillDistSyncToStripEnd', 'f4', 2),
    ('InMillExitLengthAtStand', 'f4', 10)
]

teltype_M11 = [
    ('ActualDateTime', 'i4', 8)
]

teltype_M12 = [
    ('EventCode', 'i4'),
    ('CoilIdOutCoilCut', 'S14'),
    ('CoilIdInCoilCut', 'S14'),
    ('CoilIdOutSampleCut', 'S14'),
    ('CoilIdInSampleCut', 'S14'),
    ('CoilIdOutSplitCut1', 'S14'),
    ('CoilIdOutSplitCut2', 'S14'),
    ('CoilIdInSplitCut', 'S14'),
    ('ExitLengthCutO', 'f4'),
    ('ExitLengthCutI', 'f4'),
    ('FloatSpare', 'f4', 5),
    ('IntegerSpare', 'i4', 5),
    ('CharSpare', 'S16')
]

teltype_N01 = [
    ('SystemId', 'i4'),
    ('StandNo', 'i4'),
    ('RollId', 'S8', 6),
    ('RollDiam', 'f4', 6),
    ('Crown', 'f4', 6),
    ('CrownMin', 'f4', 6),
    ('CrownMax', 'f4', 6),
    ('Roughness', 'f4', 6),
    ('Hardness', 'f4', 6),
    ('GrindType', 'i4', 6),
    ('RollQuality', 'i4', 6),
    ('RolledWeight', 'f4', 6),
    ('RolledLength', 'f4', 6),
    ('ChockIdOS', 'S8', 6),
    ('ChockIdDS', 'S8', 6)
]

teltype_N02 = [
    ('CoilId', 'S14'),
    ('CoilIdOut', 'S14'),
    ('SeqCoilOut', 'i4'),
    ('SetupNo', 'i4'),
    ('ReturnCode', 'i4'),
    ('SetupValidCode', 'i4'),
    ('NoPasses', 'i4'),
    ('AlloyCode', 'S10'),
    ('AnalysisFlag', 'i4'),
    ('AlloyComposition', 'f4', 24),
    ('Width', 'f4'),
    ('LengthStart', 'f4'),
    ('Length0', 'f4'),
    ('Length1', 'f4', 5),
    ('EntryThick', 'f4', 5),
    ('ExitThick', 'f4', 25),
    ('EntryTemp', 'f4', 5),
    ('ExitTemp', 'f4', 25),
    ('RollSpeed', 'f4', 25),
    ('TensionEntry', 'f4', 25),
    ('TensionExit', 'f4', 25),
    ('RollForceOS', 'f4', 25),
    ('RollForceDS', 'f4', 25),
    ('BendWROS', 'f4', 25),
    ('BendWRDS', 'f4', 25),
    ('BendIROS', 'f4', 25),
    ('BendIRDS', 'f4', 25),
    ('ShiftCVC', 'f4', 25),
    ('SlipForward', 'f4', 25),
    ('HydPosOS', 'f4', 25),
    ('HydPosDS', 'f4', 25),
    ('RollCoolFlow', 'f4', 2850),
    ('RollCoolPress', 'f4', 75),
    ('RollCooLimitMin', 'f4', 25),
    ('StripCoolFlow', 'f4', 180),
    ('StripCoolPress', 'f4', 60),
    ('StripModule', 'f4', 25),
    ('StandModule', 'f4', 25),
    ('TargetFlatCoeff', 'f4', 20),
    ('ThickTolLimit', 'f4', 6),
    ('FlatTolLimit', 'f4', 6),
    ('CtrlGain', 'f4', 1500),
    ('FfcCtrlUsage', 'i4', 5),
    ('FbcCtrlUsage', 'i4', 5),
    ('VfcCtrlUsage', 'i4', 5),
    ('TenLimitMax', 'f4', 30),
    ('TenLimitMin', 'f4', 30),
    ('ForceLimitMax', 'f4', 25),
    ('ForceLimitMin', 'f4', 25),
    ('ThreadHydPosOffset', 'f4', 25),
    ('ThermalCrown', 'f4', 5),
    ('DriveTorque', 'f4', 25),
    ('ThreadSpeedMode', 'i4'),
    ('StrengthLastOper', 'f4'),
    ('RollForceThread', 'f4', 5),
    ('CoeffActFctHGC', 'f4', 200),
    ('CoeffActFctWRB', 'f4', 200),
    ('CoeffActFctIRB', 'f4', 200),
    ('CoeffActFctCVC', 'f4', 200),
    ('ThreadingMode', 'i4'),
    ('TailOutMode', 'i4'),
    ('ThreadAssist', 'i4'),
    ('SpoolInd', 'i4'),
    ('SpoolOuterDiam', 'f4'),
    ('SpoolWidth', 'f4'),
    ('TargetTransLength', 'f4'),
    ('TargetPosWeldSeam', 'f4'),
    ('FlagSetupTransMode', 'i4'),
    ('TargetThickHeadLength', 'f4'),
    ('ArtifSleeveUsage', 'i4'),
    ('TensionCurveID', 'S8'),
    ('TensionCurveNoPos', 'i4'),
    ('TensionCurvePosX', 'f4', 10),
    ('TensionCurvePosY', 'f4', 10),
    ('ForceOffsetStartupTip', 'f4', 5),
    ('DifQuotRefptForce', 'f4', 50),
    ('DifQuotRefptShift', 'f4', 50),
    ('DifQuotRefptPosX', 'f4', 50),
    ('StandSwitchOff', 'i4', 5),
    ('TargetCoilTempLimit', 'f4'),
    ('ConstForceMode', 'i4'),
    ('YieldStrengthCalc', 'f4'),
    ('FloatSpare', 'f4', 5),
    ('IntegerSpare', 'i4', 5),
    ('CharSpare', 'S16')
]

teltype_N04 = [
    ('StandNo', 'i4'),
    ('ReturnCode', 'i4'),
    ('ThermCrownC0', 'f4'),
    ('ThermCrownC2', 'f4'),
    ('ThermCrownC4', 'f4')
]

teltype_N08 = [
    ('CoilId', 'S14', 25),
    ('CoilIdOut', 'S14', 25),
    ('PdiOk', 'i4', 25),
    ('Occupied', 'i4', 25),
    ('PassRolled', 'i4', 25),
    ('DispositionCode', 'i4', 25),
    ('CoilCarPosition', 'f4', 1),
    ('SampleCutSegmNo', 'i4', 2)
]

teltype_N09 = [
    ('CoilIdOut', 'S14'),
    ('StrapsNo', 'i4'),
    ('StrapCode', 'i4'),
    ('RouteCode', 'i4'),
    ('FloatSpare', 'f4', 5),
    ('IntegerSpare', 'i4', 5),
    ('CharSpare', 'S16')
]

teltype_N10 = [
    ('CoilId', 'S14'),
    ('AlloyCode', 'S10'),
    ('EntryThick', 'f4'),
    ('EntryWidth', 'f4'),
    ('EntryWidthTrim', 'f4'),
    ('CoilLength', 'f4'),
    ('StripLengthEntryPL', 'f4'),
    ('FloatSpare', 'f4', 5),
    ('IntegerSpare', 'i4', 5),
    ('CharSpare', 'S16')
]

teltype_N11 = [
    ('CoilIdOut', 'S14'),
    ('CoilIdIn', 'S14'),
    ('CoilCutType', 'i4'),
    ('CutStripExitLengthOut', 'f4'),
    ('CutCoilOutWeight', 'f4'),
    ('CutCoilOutDiam', 'f4'),
    ('CutStripExitLengthIn', 'f4'),
    ('DistDeleteCutSetpoint', 'f4'),
    ('SampleCoilIdOut', 'S14'),
    ('SampleCoilIdIn', 'S14'),
    ('SampleCutType', 'i4'),
    ('SampleLength', 'f4'),
    ('FloatSpare', 'f4', 5),
    ('IntegerSpare', 'i4', 5),
    ('CharSpare', 'S16')
]

teltype_N12 = [
    ('InMillCoilId', 'S14', 2),
    ('InMillDistSyncToStripEnd', 'f4', 2),
    ('InMillExitLengthAtStand', 'f4', 10)
]

teltype_M21 = [
    ('SegId', 'i4'),
    ('SetupId', 'i4'),
    ('CoilId', 'S14'),
    ('CoilIdOut', 'S14'),
    ('PassNo', 'i4'),
    ('TmSegStart', 'i4', 8),
    ('LenSegStart', 'f4'),
    ('TmSinceThread', 'f4'),
    ('SegType', 'i4'),
    ('LenSeg', 'f4'),
    ('TmSeg', 'f4'),
    ('VolSeg', 'f4'),
    ('NumValSeg', 'i4'),
    ('ExitThicknessGCS', 'f4', 3),
    ('ExitThicknessGCSSta', 'i4'),
    ('RollForceOS', 'f4', 3),
    ('RollForceOSSta', 'i4'),
    ('RollForceDS', 'f4', 3),
    ('RollForceDSSta', 'i4'),
    ('WrBendOS', 'f4', 3),
    ('WrBendOSSta', 'i4'),
    ('WrBendDS', 'f4', 3),
    ('WrBendDSSta', 'i4'),
    ('WrBendOpOffset', 'f4', 3),
    ('WrBendOpOffsetSta', 'i4'),
    ('IrBendOS', 'f4', 3),
    ('IrBendOSSta', 'i4'),
    ('IrBendDS', 'f4', 3),
    ('IrBendDSSta', 'i4'),
    ('IrBendOpOffset', 'f4', 3),
    ('IrBendOpOffsetSta', 'i4'),
    ('DriveRevol', 'f4', 3),
    ('DriveRevolSta', 'i4'),
    ('DrivePower', 'f4', 3),
    ('DrivePowerSta', 'i4'),
    ('DriveTorque', 'f4', 3),
    ('DriveTorqueSta', 'i4'),
    ('DriveCurrent', 'f4', 3),
    ('DriveCurrentSta', 'i4'),
    ('DriveTemp', 'f4', 3),
    ('DriveTempSta', 'i4'),
    ('RollSpeed', 'f4', 3),
    ('RollSpeedSta', 'i4'),
    ('RollRevol', 'f4', 3),
    ('RollRevolSta', 'i4'),
    ('RollTorque', 'f4', 3),
    ('RollTorqueSta', 'i4'),
    ('SlipForwCalc', 'f4', 3),
    ('SlipForwCalcSta', 'i4'),
    ('HydPosOS', 'f4', 3),
    ('HydPosOSSta', 'i4'),
    ('HydPosDS', 'f4', 3),
    ('HydPosDSSta', 'i4'),
    ('HydPosOpOffset', 'f4', 3),
    ('HydPosOpOffsetSta', 'i4'),
    ('GapPos', 'f4', 3),
    ('GapPosSta', 'i4'),
    ('Tilting', 'f4', 3),
    ('TiltingSta', 'i4'),
    ('TiltingOpOffset', 'f4', 3),
    ('TiltingOpOffsetSta', 'i4'),
    ('CVCShiftTop', 'f4', 3),
    ('CVCShiftTopSta', 'i4'),
    ('CVCShiftBot', 'f4', 3),
    ('CVCShiftBotSta', 'i4'),
    ('CVCShiftOpOffset', 'f4', 3),
    ('CVCShiftOpOffsetSta', 'i4'),
    ('RollCoolTemp', 'f4', 3),
    ('RollCoolTempSta', 'i4'),
    ('RollCollPress', 'f4', 9),
    ('RollCollPressSta', 'i4', 3),
    ('RollCoolDist', 'f4', 114),
    ('RollCoolDistSta', 'i4', 3),
    ('GcsActive', 'i4'),
    ('FcsActive', 'i4'),
    ('PgmActive', 'i4'),
    ('MillState', 'i4'),
    ('NumMeasStripPhase', 'i4', 6),
    ('ActiveSetup', 'i4'),
    ('StandAvailable', 'i4'),
    ('EntryTensionOS', 'f4', 3),
    ('EntryTensionOSSta', 'i4'),
    ('EntryTensionDS', 'f4', 3),
    ('EntryTensionDSSta', 'i4'),
    ('ExitTensionOS', 'f4', 3),
    ('ExitTensionOSSta', 'i4'),
    ('ExitTensionDS', 'f4', 3),
    ('ExitTensionDSSta', 'i4'),
    ('EntryStripSpeed', 'f4', 3),
    ('EntryStripSpeedSta', 'i4'),
    ('ExitStripSpeed', 'f4', 3),
    ('ExitStripSpeedSta', 'i4'),
    ('AxialFrShiftTop', 'f4', 3),
    ('AxialFrShiftTopSta', 'i4'),
    ('AxialFrShiftBot', 'f4', 3),
    ('AxialFrShiftBotSta', 'i4'),
    ('LoadCellFrOS', 'f4', 3),
    ('LoadCellFrOSSta', 'i4'),
    ('LoadCellFrDS', 'f4', 3),
    ('LoadCellFrDSSta', 'i4'),
    ('PgmOffsetWrBending', 'f4', 3),
    ('PgmOffsetWrBendingSta', 'i4'),
    ('PgmOffsetIrBending', 'f4', 3),
    ('PgmOffsetIrBendingSta', 'i4'),
    ('PgmOffsetShift', 'f4', 3),
    ('PgmOffsetShiftSta', 'i4'),
    ('FcsOffsetWrBending', 'f4', 3),
    ('FcsOffsetWrBendingSta', 'i4'),
    ('FcsOffsetIrBending', 'f4', 3),
    ('FcsOffsetIrBendingSta', 'i4'),
    ('FcsOffsetShift', 'f4', 3),
    ('FcsOffsetShiftSta', 'i4'),
    ('RefWrBendingSetup', 'f4'),
    ('RefWrBendingSetupSta', 'i4'),
    ('RefIrBendingSetup', 'f4'),
    ('RefIrBendingSetupSta', 'i4'),
    ('RefShiftSetup', 'f4'),
    ('RefShiftSetupSta', 'i4'),
    ('RefTiltSetup', 'f4'),
    ('RefTiltSetupSta', 'i4'),
    ('RefGapSetup', 'f4'),
    ('RefGapSetupSta', 'i4'),
    ('LDCThickCorrOp', 'f4'),
    ('LDCThickCorrOpSta', 'i4'),
    ('LDCThickCorrAuto', 'f4'),
    ('LDCThickCorrAutoSta', 'i4')
]

teltype_M22 = [
    ('SegId', 'i4'),
    ('SetupId', 'i4'),
    ('CoilId', 'S14'),
    ('CoilIdOut', 'S14'),
    ('PassNo', 'i4'),
    ('TmSegStart', 'i4', 8),
    ('LenSegStart', 'f4'),
    ('TmSinceThread', 'f4'),
    ('SegType', 'i4'),
    ('LenSeg', 'f4'),
    ('TmSeg', 'f4'),
    ('VolSeg', 'f4'),
    ('NumValSeg', 'i4'),
    ('StripTemp', 'f4', 3),
    ('StripTempSta', 'i4'),
    ('StripSpeed', 'f4', 3),
    ('StripSpeedSta', 'i4'),
    ('StripThick', 'f4', 4),
    ('StripThickSta', 'i4'),
    ('ThickDev', 'f4', 3),
    ('ThickDevSta', 'i4'),
    ('StripWidth', 'f4', 3),
    ('StripWidthSta', 'i4'),
    ('TensionOpOffset', 'f4', 3),
    ('TensionOpOffsetSta', 'i4'),
    ('TargetThick', 'f4'),
    ('TargetThickSta', 'i4'),
    ('FlatnessVal', 'f4', 60),
    ('FlatnessValSta', 'i4'),
    ('FlatnessRollRevol', 'f4', 3),
    ('FlatnessRollRevolSta', 'i4'),
    ('FlatnessRollCurrent', 'f4', 3),
    ('FlatnessRollCurrentSta', 'i4'),
    ('FlatnessRollTorque', 'f4', 3),
    ('FlatnessRollTorqueSta', 'i4'),
    ('TargetFlatCoeff', 'f4', 4),
    ('TargetFlatCoeffSta', 'i4'),
    ('MeasFlatCoeff', 'f4', 4),
    ('MeasFlatCoeffSta', 'i4'),
    ('OffCentreExit', 'f4', 3),
    ('OffCentreExitSta', 'i4'),
    ('StripCoolTemp', 'f4', 3),
    ('StripCoolTempSta', 'i4'),
    ('StripCoolPress', 'f4', 6),
    ('StripCoolPressSta', 'i4', 2),
    ('StripCoolDist', 'f4', 6),
    ('StripCoolDistSta', 'i4'),
    ('NumMeasStripPhase', 'i4', 6)
]

teltype_M23 = [
    ('SegId', 'i4'),
    ('SetupId', 'i4'),
    ('CoilId', 'S14'),
    ('CoilIdOut', 'S14'),
    ('PassNo', 'i4'),
    ('TmSegStart', 'i4', 8),
    ('LenSegStart', 'f4'),
    ('TmSinceThread', 'f4'),
    ('SegType', 'i4'),
    ('LenSeg', 'f4'),
    ('TmSeg', 'f4'),
    ('VolSeg', 'f4'),
    ('NumValSeg', 'i4'),
    ('StripTemp', 'f4', 3),
    ('StripTempSta', 'i4'),
    ('StripSpeed', 'f4', 3),
    ('StripSpeedSta', 'i4'),
    ('StripThick', 'f4', 4),
    ('StripThickSta', 'i4'),
    ('ThickDev', 'f4', 3),
    ('ThickDevSta', 'i4'),
    ('StripWidth', 'f4', 3),
    ('StripWidthSta', 'i4'),
    ('TensionOpOffset', 'f4', 3),
    ('TensionOpOffsetSta', 'i4'),
    ('TargetThick', 'f4'),
    ('TargetThickSta', 'i4'),
    ('PayoffReelRevol', 'f4', 3),
    ('PayoffReelRevolSta', 'i4'),
    ('PayoffReelPower', 'f4', 3),
    ('PayoffReelPowerSta', 'i4'),
    ('PayoffReelCurrent', 'f4', 3),
    ('PayoffReelCurrentSta', 'i4'),
    ('PayoffReelTorque', 'f4', 3),
    ('PayoffReelTorqueSta', 'i4'),
    ('DeflectRollRevol', 'f4', 3),
    ('DeflectRollRevolSta', 'i4'),
    ('DeflectRollCurrent', 'f4', 3),
    ('DeflectRollCurrentSta', 'i4'),
    ('DeflectRollTorque', 'f4', 3),
    ('DeflectRollTorqueSta', 'i4'),
    ('CoilDiamInner', 'f4', 3),
    ('CoilDiamInnerSta', 'i4'),
    ('CoilDiamOuter', 'f4', 3),
    ('CoilDiamOuterSta', 'i4'),
    ('OffCentreEntry', 'f4', 3),
    ('OffCentreEntrySta', 'i4'),
    ('NumMeasStripPhase', 'i4', 6)
]

teltype_M24 = [
    ('SegId', 'i4'),
    ('SetupId', 'i4'),
    ('CoilId', 'S14'),
    ('CoilIdOut', 'S14'),
    ('PassNo', 'i4'),
    ('TmSegStart', 'i4', 8),
    ('LenSegStart', 'f4'),
    ('TmSinceThread', 'f4'),
    ('SegType', 'i4'),
    ('LenSeg', 'f4'),
    ('TmSeg', 'f4'),
    ('VolSeg', 'f4'),
    ('NumValSeg', 'i4'),
    ('StripTemp', 'f4', 3),
    ('StripTempSta', 'i4'),
    ('StripSpeed', 'f4', 3),
    ('StripSpeedSta', 'i4'),
    ('StripThick', 'f4', 4),
    ('StripThickSta', 'i4'),
    ('ThickDev', 'f4', 3),
    ('ThickDevSta', 'i4'),
    ('StripWidth', 'f4', 3),
    ('StripWidthSta', 'i4'),
    ('TensionOpOffset', 'f4', 3),
    ('TensionOpOffsetSta', 'i4'),
    ('TargetThick', 'f4'),
    ('TargetThickSta', 'i4'),
    ('FlatnessVal', 'f4', 60),
    ('FlatnessValSta', 'i4'),
    ('FlatnessRollRevol', 'f4', 3),
    ('FlatnessRollRevolSta', 'i4'),
    ('FlatnessRollCurrent', 'f4', 3),
    ('FlatnessRollCurrentSta', 'i4'),
    ('FlatnessRollTorque', 'f4', 3),
    ('FlatnessRollTorqueSta', 'i4'),
    ('TargetFlatCoeff', 'f4', 4),
    ('TargetFlatCoeffSta', 'i4'),
    ('MeasFlatCoeff', 'f4', 4),
    ('MeasFlatCoeffSta', 'i4'),
    ('CoilerInUse', 'i4'),
    ('TensionReelRevol', 'f4', 3),
    ('TensionReelRevolSta', 'i4'),
    ('TensionReelPower', 'f4', 3),
    ('TensionReelPowerSta', 'i4'),
    ('CoilDiamInner', 'f4', 6),
    ('CoilDiamInnerSta', 'i4', 2),
    ('CoilDiamOuter', 'f4', 6),
    ('CoilDiamOuterSta', 'i4', 2),
    ('OffCentreExit', 'f4', 3),
    ('OffCentreExitSta', 'i4'),
    ('CoilIdInOnCoiler', 'S14', 2),
    ('CoilIdOutOnCoiler', 'S14', 2),
    ('StripLengthCoiler', 'f4', 2),
    ('SpoolInd', 'i4'),
    ('SpoolDiamOuter', 'f4'),
    ('SpoolDiamInner', 'f4'),
    ('SpoolWidth', 'f4'),
    ('NumMeasStripPhase', 'i4', 6),
    ('ARUActivePower', 'f4', 3),
    ('ARUActivePowerSta', 'i4'),
    ('ARUCurrent', 'f4', 3),
    ('ARUCurrentSta', 'i4'),
    ('LVPower', 'f4', 3),
    ('LVPowerSta', 'i4'),
    ('LVLineCurrent', 'f4', 3),
    ('LVLineCurrentSta', 'i4'),
    ('LVDCVoltage', 'f4', 3),
    ('LVDCVoltageSta', 'i4')
]

teltype_M25 = [
    ('CoilIdOut', 'S14'),
    ('PassNo', 'i4'),
    ('SetupNo', 'i4'),
    ('AlloyCode', 'S10'),
    ('CoilDiamExit', 'f4'),
    ('LengthStripExit', 'f4'),
    ('LengthPhaseExit', 'f4', 3),
    ('ThickMeasDev', 'f4', 9),
    ('ThickMeasStdDev', 'f4', 3),
    ('FlatMeasDev', 'f4', 9),
    ('ExitStripTemp', 'f4', 9),
    ('EntryThick', 'f4', 12),
    ('ExitThick', 'f4', 60),
    ('RollForce', 'f4', 60),
    ('RollForceDiff', 'f4', 45),
    ('Tilting', 'f4', 45),
    ('WorkRollBend', 'f4', 45),
    ('InterRollBend', 'f4', 45),
    ('CVCShiftTop', 'f4', 45),
    ('CVCShiftBot', 'f4', 45),
    ('RollSpeed', 'f4', 45),
    ('EntryStripSpeed', 'f4', 9),
    ('ExitStripSpeed', 'f4', 45),
    ('EntryTens', 'f4', 9),
    ('ExitTens', 'f4', 45),
    ('RollTorque', 'f4', 45),
    ('RollCoolTemp', 'f4', 45),
    ('RollCoolPress', 'f4', 45),
    ('RollCoolFlow', 'f4', 45),
    ('LengthThickTol', 'f4', 3),
    ('LengthFlatTol', 'f4', 3),
    ('StartDateTime', 'i4', 8),
    ('FinishDateTime', 'i4', 8),
    ('DefectNo', 'i4'),
    ('DefectLengthBegin', 'f4', 12),
    ('DefectLengthEnd', 'f4', 12),
    ('WeldNo', 'i4'),
    ('LengthWeldSeams', 'f4', 4),
    ('CoilIdIn', 'S14', 4),
    ('ThreadHydPos', 'f4', 5),
    ('ThreadTilting', 'f4', 5),
    ('ThreadBendWorkRoll', 'f4', 5),
    ('ThreadBendInterRoll', 'f4', 5),
    ('ThreadCVCShiftTop', 'f4', 5),
    ('ThreadCVCShiftTBot', 'f4', 5),
    ('OffGaugeLenHead', 'f4'),
    ('OffGaugeLenTail', 'f4'),
    ('ThickDevLimitTrans', 'f4'),
    ('ThickDevLimitBody', 'f4'),
    ('FlatDevLimitTrans', 'f4'),
    ('FlatDevLimitBody', 'f4'),
    ('ThickDev2SigTrans', 'f4'),
    ('ThickDev2SigBody', 'f4'),
    ('FlatDev2SigTrans', 'f4'),
    ('FlatDev2SigBody', 'f4'),
    ('RefStripWidth', 'f4'),
    ('OffCentreEntry', 'f4', 9),
    ('DeflRollEntryTens', 'f4', 9),
    ('DeflRollForceDiff', 'f4', 9),
    ('SlipForwd', 'f4', 45),
    ('DriveCurrent', 'f4', 45),
    ('DrivePower', 'f4', 45),
    ('FloatSpare', 'f4', 5),
    ('IntegerSpare', 'i4', 5),
    ('CharSpare', 'S16')
]

teltype_M26 = [
    ('CoilIdOut', 'S14'),
    ('PassNo', 'i4'),
    ('ActualDateTime', 'i4', 8),
    ('Thickness', 'f4', 10),
    ('ThicknessStdDev', 'f4', 10),
    ('Flatness', 'f4', 600),
    ('Length', 'f4', 10),
    ('FlatnessDev', 'f4', 10),
    ('StripSpeed', 'f4', 10),
    ('AccelFlag', 'i4', 10),
    ('GcsActive', 'i4', 50),
    ('FcsActive', 'i4', 50),
    ('NoOfSamples', 'i4')
]
